@LedgerMock_HostAddress = http://localhost:5287
@IdempotencyKey = {{$guid}}

### 1. Deposit
POST {{LedgerMock_HostAddress}}/accounts/acc-001/deposit
Content-Type: application/json

{
  "amountInCents": 20000,
  "idempotencyKey": "{{IdempotencyKey}}"
}

### 2. Withdraw
POST {{LedgerMock_HostAddress}}/accounts/acc-001/withdraw
Content-Type: application/json

{
  "amountInCents": 5000,
  "idempotencyKey": "{{IdempotencyKey}}"
}

### 3. Atomic Transfer between Account 1 and Account 2
POST {{LedgerMock_HostAddress}}/transfers
Content-Type: application/json

{
  "sourceAccountId": "acc-001",
  "destinationAccountId": "acc-002",
  "amountInCents": 7500,
  "idempotencyKey": "{{IdempotencyKey}}"
}

### 4. Get Account 1 Balance
GET {{LedgerMock_HostAddress}}/accounts/acc-001/balance

### 5. Get Account 2 Balance
GET {{LedgerMock_HostAddress}}/accounts/acc-002/balance
